import type { GenerationProvider, ProviderResult, ProviderStatus, SubmitArgs } from "./types";
import type { AnyModel } from "@/lib/models";
import { IMAGE_SIZES, type ImageSizeId } from "@/lib/models";

/**
 * The mock provider. Development and demos cost nothing.
 *
 * It is deliberately stateless: everything needed to answer status() and
 * result() is encoded in the request id, so it behaves identically across
 * serverless invocations where a module-level map would not survive.
 *
 *   mock:<mode>:<startedAtMs>:<count>:<nonce>
 *
 * Prompts can steer it, which is how failure and safety paths get exercised
 * without burning provider credits:
 *   [[fail]] → the job fails    [[nsfw]] → flagged    [[slow]] → 20s render
 */

const QUEUED_MS = 1_200;
const RUNNING_MS = 3_800;
const SLOW_RUNNING_MS = 20_000;

type MockMode = "ok" | "fail" | "nsfw" | "slow";

export const MOCK_DIRECTIVES: Record<Exclude<MockMode, "ok">, string> = {
  fail: "[[fail]]",
  nsfw: "[[nsfw]]",
  slow: "[[slow]]",
};

function modeFromPrompt(prompt: string): MockMode {
  const lowered = prompt.toLowerCase();
  if (lowered.includes(MOCK_DIRECTIVES.fail)) return "fail";
  if (lowered.includes(MOCK_DIRECTIVES.nsfw)) return "nsfw";
  if (lowered.includes(MOCK_DIRECTIVES.slow)) return "slow";
  return "ok";
}

function parseRequestId(requestId: string) {
  const [, mode, startedAt, count, nonce] = requestId.split(":");
  return {
    mode: (mode ?? "ok") as MockMode,
    startedAt: Number(startedAt ?? 0),
    count: Math.max(1, Number(count ?? 1)),
    nonce: nonce ?? "0",
  };
}

function elapsed(startedAt: number) {
  return Date.now() - startedAt;
}

function runningFor(mode: MockMode) {
  return mode === "slow" ? SLOW_RUNNING_MS : RUNNING_MS;
}

export const mockProvider: GenerationProvider = {
  name: "mock",

  async submit({ params }: SubmitArgs) {
    const mode = modeFromPrompt(String(params.prompt ?? ""));
    const nonce = Math.random().toString(36).slice(2, 10);
    const count = Number(params.num_images ?? 1);
    return { providerRequestId: `mock:${mode}:${Date.now()}:${count}:${nonce}` };
  },

  async status(_model: AnyModel, providerRequestId: string): Promise<ProviderStatus> {
    const { mode, startedAt } = parseRequestId(providerRequestId);
    const age = elapsed(startedAt);

    if (age < QUEUED_MS) return { state: "queued", queuePosition: 1 };
    if (age < runningFor(mode)) return { state: "running" };

    if (mode === "fail") {
      return { state: "failed", error: "Mock provider: forced failure ([[fail]])" };
    }
    if (mode === "nsfw") {
      return { state: "nsfw", error: "Mock provider: output flagged ([[nsfw]])" };
    }
    return { state: "completed" };
  },

  async result(model: AnyModel, providerRequestId: string): Promise<ProviderResult> {
    const { mode, nonce, count } = parseRequestId(providerRequestId);
    if (mode === "nsfw") return { assets: [], flagged: true };

    // Sample outputs are generated by us, on our own domain — nothing borrowed.
    const size = (model.kind === "image" ? "square_hd" : "landscape_16_9") as ImageSizeId;
    const { width, height } = IMAGE_SIZES[size];

    return {
      assets: Array.from({ length: count }, (_, index) => ({
        kind: "image" as const,
        url: `/api/mock/media/${nonce}-${index}.svg?w=${width}&h=${height}`,
        width,
        height,
      })),
    };
  },

  async cancel() {
    // Nothing to tell: cancellation is recorded on our side.
  },
};
